---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)

```

# Reading Data

```{r warning = FALSE}

# Reading in the three datasets.

anes88_national <- spss.get("raw_data/anes/anes88-national.por", use.value.labels=TRUE)
anes88_st <- spss.get("raw_data/anes/anes88-super-tuesday.por", use.value.labels=TRUE)
anes84_national <- spss.get("raw_data/anes/anes84-national.por", use.value.labels=TRUE)
anes84_cm <- spss.get("raw_data/anes/anes84-continuous-monitoring.por", use.value.labels=TRUE)
anes80_national <- spss.get("raw_data/anes/anes80-national.por", use.value.labels=TRUE)
anes80_mp <- spss.get("raw_data/anes/anes80-major-panel.por", use.value.labels=TRUE)

```


<!-- ```{r} -->
<!-- names(anes80_mp) -->
<!-- ``` -->


# Cleaning Data (Part One)

```{r}

# Cleaning the 1988 dataset
# Case 0

anes88_st_clean_0 <- anes88_st %>%
  
  # Voting from VST0457 to VST0462
  # Feeling thermometers from VST0171 to VST0189
  # Traits from VST0301 to VST0424
  # Ideology from VST0425 to VST0441
  # Viability from VST0229 to VST0241
  # Electability from VST0242 to VST0254
  
  select(VST0001, VST0457:VST0462, VST0171:VST0189, VST0301:VST0424,
         VST0425:VST0441, VST0229:VST0241, VST0242:VST0254)

# Case 1

anes88_st_clean1 <- anes88_st %>%

  # Voting from VST1528 to VST1561
  # Feeling thermometers from VST1301 to VST1317
  # Traits from VST1409 to VST1527
  # Ideology not asked
  # Viability from VST1322 to VST1331
  # Electability from VST1332 to VST1341 

  select(VST1001, VST1528:VST1561, VST1301:VST1317, VST1409:VST1527,
         VST1322:VST1331, VST1332:VST1341)

# Cleaning the 1984 dataset

anes84_cm_clean <- anes84_cm %>%
  
  # Voting from VCM0735 to VCM0736.
  # Feeling thermometers from VCM0219 to VCM0236.
  # Traits from VCM0418 to VCM0573
  # Ideology from VCM0610 to VCM0637.
  # Viability from VCM0311 to VCM0316.
  # Electability from VCM1001 to VCM1007.

  select(VCM0001, VCM0735:VCM0736, VCM0219:VCM0236,
         VCM0418:VCM0573, VCM0610:VCM0637, VCM0311:VCM0316, VCM1001:VCM1007)
  
# Cleaning the 1980 dataset.

anes80_mp_clean <- anes80_mp %>%

  # TODO
  # Voting from VMP4078 to VMP4079
  # Feeling thermometers from VMP3095 to VMP3112
  # Traits from VMP0074 to VMP0115
  # Ideology from VMP2125 to VMP2136
  # Viability from VMP0192 to VMP0203 and from VMP0217 to VMP0231
  # Electability from VMP0204 to VMP0205 and from VMP0232 to VMP0233

  select(VMP4078:VMP4079, VMP3095:VMP3112, VMP0074:VMP0115,
         VMP2125:VMP2136, VMP0192:VMP0203, VMP0217:VMP0231,
         VMP0204:VMP0205, VMP0232:VMP0233)

```

# Cleaning Data (Part Two)

## repositioning columns  

```{r}
df88st <- anes88_st %>%
  
  # Select ID, voting, lib/con and feeling thermometer, viability, electability, ...
  
  # Voting from VST0457 to VST0462
  # Feeling thermometers from VST0171 to VST0189
  # Traits from VST0301 to VST0424
  # Ideology from VST0425 to VST0441
  # Viability from VST0229 to VST0241
  # Electability from VST0242 to VST0254  
  
  select(VST0001, VST0459, 
         VST0171, VST0172, VST0173, VST0175, VST0176,
         VST0229, VST0230, VST0231, VST0233, VST0234,
         VST0242, VST0243, VST0244, VST0246, VST0247,
         
         VST0425, 
         VST0428, VST0429, VST0430, VST0432, VST0433,
         
         VST0304, VST0306, VST0307, VST0308, 
         VST0312, VST0314, VST0315, VST0316, 
         VST0320, VST0322, VST0323, VST0324,
         VST0336, VST0338, VST0339, VST0340, 
         VST0344, VST0346, VST0347, VST0348
         )

# rename columns

my_candidate <- c("GORE","DUKAKIS","HART","JACKSON","GEPHARDT")
my_candidate_id <- as.integer(c(14, 12, 15, 16, 13))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2", "Feeling3", "Feeling4", "Feeling5",
              "Viability1", "Viability2", "Viability3", "Viability4", "Viability5",
              "Electability1", "Electability2", "Electability3", "Electability4", "Electability5",
              
              "Ideology", 
              "Ideology1", "Ideology2", "Ideology3", "Ideology4", "Ideology5",
              
              "Inspire1", "Decent1", "Cares1", "Know1",
              "Inspire2", "Decent2", "Cares2", "Know2",
              "Inspire3", "Decent3", "Cares3", "Know3",
              "Inspire4", "Decent4", "Cares4", "Know4",
              "Inspire5", "Decent5", "Cares5", "Know5"
              )

colnames(df88st) <- my_names
```


```{r}
df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors=FALSE)
df88st <-merge(df88st, df, by.x = "voting", by.y = "my_candidate_id", all.x=TRUE)
names(df88st)[names(df88st)=="my_candidate"] <- "VoteCandidate"
```


```{r eval=FALSE, include=FALSE}

# verify column renaming, candidates and their number 1-5 mapping must be correct.

str(df88st)

```


## Normalize ratings


<!-- ```{r} -->

<!-- # Cleaning 1988 case 0 -->

<!-- anes88_st_clean_0_d <- anes88_st_clean_0 %>% -->

<!--   # Select ID, voting, feeling thermometer, viability, electability, and columns -->

<!--   select(VST0001, VST0459, -->
<!--          VST0171, VST0172, VST0173, VST0175, VST0176, -->
<!--          VST0229, VST0230, VST0231, VST0233, VST0234, -->
<!--          VST0242, VST0243, VST0244, VST0246, VST0247, -->
<!--          VST0425, VST0428, VST0429, VST0430, VST0432, VST0433, -->
<!--          VST0304, VST0306:VST0308, VST0312, VST0314:VST0316, VST0320, VST0322:VST0324, VST0336, VST0338:VST0340, VST0344, VST0346:VST0348) %>% -->

<!--   # VST0301:VST0309, VST0310:VST0318, VST0319:VST0327, VST0333:VST0340, VST0341:VST0348) %>% -->

<!--   # Normalize feeling thermometers -->

<!--   rowwise(VST0001) %>% -->
<!--   mutate(NORMALIZED_FT_gore = (VST0171 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) /  -->
<!--            (max(VST0171, VST0172, VST0173, VST0175, VST0176) - -->
<!--               min(VST0171, VST0172, VST0173, VST0175, VST0176)), -->
<!--          NORMALIZED_FT_dukakis = (VST0172 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) /  -->
<!--            (max(VST0171, VST0172, VST0173, VST0175, VST0176) - -->
<!--               min(VST0171, VST0172, VST0173, VST0175, VST0176)), -->
<!--          NORMALIZED_FT_hart = (VST0173 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) /  -->
<!--            (max(VST0171, VST0172, VST0173, VST0175, VST0176) - -->
<!--               min(VST0171, VST0172, VST0173, VST0175, VST0176)), -->
<!--          NORMALIZED_FT_jackson = (VST0175 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) /  -->
<!--            (max(VST0171, VST0172, VST0173, VST0175, VST0176) - -->
<!--               min(VST0171, VST0172, VST0173, VST0175, VST0176)), -->
<!--          NORMALIZED_FT_gephardt = (VST0176 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) /  -->
<!--            (max(VST0171, VST0172, VST0173, VST0175, VST0176) - -->
<!--               min(VST0171, VST0172, VST0173, VST0175, VST0176))) %>% -->
<!--   drop_na(NORMALIZED_FT_gore) %>% -->

<!--   # Normalize viability -->

<!--   rowwise(VST0001) %>% -->
<!--   mutate(NORMALIZED_VIABILITY_gore = VST0229 / sum(VST0229, VST0230, VST0231, VST0233, VST0234), -->
<!--          NORMALIZED_VIABILITY_dukakis = VST0230 / sum(VST0229, VST0230, VST0231, VST0233, VST0234), -->
<!--          NORMALIZED_VIABILITY_hart = VST0231 / sum(VST0229, VST0230, VST0231, VST0233, VST0234), -->
<!--          NORMALIZED_VIABILITY_jackson = VST0233 / sum(VST0229, VST0230, VST0231, VST0233, VST0234), -->
<!--          NORMALIZED_VIABILITY_gephardt = VST0234 / sum(VST0229, VST0230, VST0231, VST0233, VST0234)) %>% -->
<!--   drop_na(NORMALIZED_VIABILITY_gore) %>% -->

<!--   # Normalize electability -->

<!--   rowwise(VST0001) %>% -->
<!--   mutate(NORMALIZED_ELECTABILITY_gore = VST0242 / sum(VST0242, VST0243, VST0244, VST0246, VST0247), -->
<!--          NORMALIZED_ELECTABILITY_dukakis = VST0243 / sum(VST0242, VST0243, VST0244, VST0246, VST0247), -->
<!--          NORMALIZED_ELECTABILITY_hart = VST0244 / sum(VST0242, VST0243, VST0244, VST0246, VST0247), -->
<!--          NORMALIZED_ELECTABILITY_jackson = VST0246 / sum(VST0242, VST0243, VST0244, VST0246, VST0247), -->
<!--          NORMALIZED_ELECTABILITY_gephardt = VST0247 / sum(VST0242, VST0243, VST0244, VST0246, VST0247)) %>% -->
<!--   drop_na(NORMALIZED_ELECTABILITY_gore) %>% -->

<!--   # Manipulate ideological distance -->

<!--   rowwise(VST0001) %>% -->
<!--   mutate(IDEOLOGY_gore = square(VST0425 - VST0428), -->
<!--          IDEOLOGY_dukakis = square(VST0425 - VST0429), -->
<!--          IDEOLOGY_hart = square(VST0425 - VST0430), -->
<!--          IDEOLOGY_jackson = square(VST0425 - VST0432), -->
<!--          IDEOLOGY_gephardt = square(VST0425 - VST0433)) %>% -->

<!--   # Average candidate traits -->

<!--   rowwise(VST0001) -->
<!--   mutate(TRAITS_gore = mean(VST0304, VST0306, VST0307, VST0308), -->
<!--          TRAITS_dukakis = mean(VST0312, VST0314, VST0315, VST0316), -->
<!--          TRAITS_hart = mean(VST0320, VST0322, VST0323, VST0324), -->
<!--          TRAITS_jackson = mean(VST0336, VST0338, VST0339, VST0340), -->
<!--          TRAITS_gephardt = mean(VST0344, VST0346, VST0347, VST0348))  -->
<!-- ``` -->

<!-- Need to scale ideological distance.  -->

```{r warning=FALSE}

# 1) Normalize feeling thermometers

my_rescale1 <- function(X) round((X - min(X, na.rm = TRUE))/ (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)

# NORMALIZED_FT
df88st[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", "NORMALIZED_FT4", "NORMALIZED_FT5")] <- t(apply(df88st[, c("Feeling1", "Feeling2", "Feeling3", "Feeling4", "Feeling5")], MARGIN = 1, FUN = my_rescale1))


# 2) Normalize viability

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# NORMALIZED_VIABILITY
df88st[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", "NORMALIZED_VIABILITY5")] <- t(apply(df88st[, c("Viability1", "Viability2", "Viability3", "Viability4", "Viability5")], MARGIN = 1, FUN = my_rescale2))

# NORMALIZED_ELECTABILITY 
df88st[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", "NORMALIZED_ELECTABILITY5")] <- t(apply(df88st[, c("Electability1", "Electability2", "Electability3", "Electability4", "Electability5")], MARGIN = 1, FUN = my_rescale2))


# 3) Manipulate ideological distance

# IDEOLOGY
df88st[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", "NORMALIZED_IDEOLOGY5")] <- square(df88st[, c("Ideology1", "Ideology2", "Ideology3", "Ideology4", "Ideology5")] - df88st[, "Ideology"])

# rescale ideological distance

df88st[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", "NORMALIZED_IDEOLOGY5")] <- t(apply(df88st[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", "NORMALIZED_IDEOLOGY5")], MARGIN = 1, FUN = my_rescale1))


# 4) Average candidate traits

# TRAITS
df88st$TRAITS1 = abs(rowMeans(df88st[, c("Inspire1", "Decent1", "Cares1", "Know1")], na.rm = TRUE) - 6) / 5
df88st$TRAITS2 = abs(rowMeans(df88st[, c("Inspire2", "Decent2", "Cares2", "Know2")], na.rm = TRUE) - 6) / 5
df88st$TRAITS3 = abs(rowMeans(df88st[, c("Inspire3", "Decent3", "Cares3", "Know3")], na.rm = TRUE) - 6) / 5
df88st$TRAITS4 = abs(rowMeans(df88st[, c("Inspire4", "Decent4", "Cares4", "Know4")], na.rm = TRUE) - 6) / 5
df88st$TRAITS5 = abs(rowMeans(df88st[, c("Inspire5", "Decent5", "Cares5", "Know5")], na.rm = TRUE) - 6) / 5


# 5) Convert NaN to NA

df88st[df88st=="NaN"] <- NA

```
 
 
 
```{r}

# verify  calculations

df88st[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", "NORMALIZED_FT4", "NORMALIZED_FT5", "Feeling1", "Feeling2", "Feeling3", "Feeling4", "Feeling5")]
df88st[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", "NORMALIZED_VIABILITY5", "Viability1", "Viability2", "Viability3", "Viability4", "Viability5")]
df88st[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", "NORMALIZED_ELECTABILITY5", "Electability1", "Electability2", "Electability3", "Electability4", "Electability5")]
df88st[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", "NORMALIZED_IDEOLOGY5", "Ideology1", "Ideology2", "Ideology3", "Ideology4", "Ideology5")]
df88st[, c("TRAITS1", "Inspire1", "Decent1", "Cares1", "Know1")]
df88st[, c("TRAITS2", "Inspire2", "Decent2", "Cares2", "Know2")]
df88st[, c("TRAITS3", "Inspire3", "Decent3", "Cares3", "Know3")]
df88st[, c("TRAITS4", "Inspire4", "Decent4", "Cares4", "Know4")]
df88st[, c("TRAITS5", "Inspire5", "Decent5", "Cares5", "Know5")]

```
 
 

# Pivoting Data (Part Two)

<!-- ```{r} -->

<!-- anes88_st_clean_0_d_pivot <- anes88_st_clean_0_d %>% -->
<!--   select(VST0001, VST0459, 67:91) %>% -->
<!--   na.omit() %>% -->
<!--   pivot_longer(cols = c(NORMALIZED_FT_gore, NORMALIZED_FT_dukakis, -->
<!--                         NORMALIZED_FT_hart, NORMALIZED_FT_jackson, NORMALIZED_FT_gephardt), -->
<!--                names_to = "candidate", values_to = "normalized_ft") -->



<!-- ``` -->

```{r}

# 1) Subset: df88st_normalized_ft

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", "NORMALIZED_FT4", "NORMALIZED_FT5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df


# 2) Subset: df88st_normalized_viability

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", "NORMALIZED_VIABILITY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))

# convert VotingCandata to 1, 0
df_final$VoteCandidate <-  1 * (df_final$Candidate == df_final$VoteCandidate)

# 3) Subset: df88st_normalized_electability

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", "NORMALIZED_ELECTABILITY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))


# 4) Subset: df88st_normalized_ideology

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", "NORMALIZED_IDEOLOGY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))


# 5) Subset: df88st_traits

my_cols <- c("ID", "TRAITS1", "TRAITS2", "TRAITS3", "TRAITS4", "TRAITS5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "TRAITS", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))

```

```{r}

df_final %>%
  drop_na() %>%
  write.dta("clean_data/df88st_d.dta")

```


```{r include=FALSE}
rm(list=ls())
```

