---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)
library(foreign)

```


# Reading Data

```{r warning = FALSE}

naes00 <- read.spss("raw_data/naes/NAES-2000-Nat-CS-19991214-20000403-Data.sav", to.data.frame=TRUE, use.value.labels=FALSE)
naes00[naes00 == 998] <- NA
naes00[naes00 == 999] <- NA

```


## Cleaning Data

## Repositioning columns  

```{r}

df00 <- naes00 %>%

  # Voting cR12
  # Feeling thermometers cA11, cA30
  # Traits from cA12, cA13, cA14, cA15, cA31, cA32, cA33, cA34
  # Ideology cA19, cA37
  # Viability from cN04 to cN05
  # Electability from cN07/cN09 to cN11/cN13 (**need to note reason for choosing Bush)
  
  select(ckey, cr12, 
         ca11, ca30, 
         cn04, cn05, 
         cn07, cn11,
         
         cv04, 
         ca19, ca37, 
         
         ca12, ca13, ca14, ca15, 
         ca31, ca32, ca33, ca34
         )

# rename columns

my_candidate <- c("GORE", "BRADLEY")
my_candidate_id <- as.integer(c(2, 1))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2",
              "Viability1", "Viability2", 
              "Electability1", "Electability2", 
              
              "Ideology", 
              "Ideology1", "Ideology2", 
              
              "Cares1", "Honest1", "Inspire1", "Know1",
              "Cares2", "Honest2", "Inspire2", "Know2"
              )

colnames(df00) <- my_names

```


```{r}

df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors=FALSE)
df00 <-merge(df00, df, by.x = "voting", by.y = "my_candidate_id", all.x=TRUE)
names(df00)[names(df00)=="my_candidate"] <- "VoteCandidate"

```


```{r eval=FALSE, include=FALSE}

# verify column renaming, candidates and their number 1-5 mapping must be correct.

str(df00)

```


## Normalize ratings

```{r warning=FALSE}

# 1) Normalize feeling thermometers

my_rescale1 <- function(X) { 
  if (max(X, na.rm = TRUE) == min(X, na.rm = TRUE)) 
    X / sum(X, na.rm = TRUE)
  else
    round((X - min(X, na.rm = TRUE)) / (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)
}

# NORMALIZED_FT
df00[, c("NORMALIZED_FT1", "NORMALIZED_FT2")] <- t(apply(df00[, c("Feeling1", "Feeling2")], MARGIN = 1, FUN = my_rescale1))


# 2) Normalize viability

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# NORMALIZED_VIABILITY
df00[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")] <- t(apply(df00[, c("Viability1", "Viability2")], MARGIN = 1, FUN = my_rescale2))

# NORMALIZED_ELECTABILITY 
df00[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")] <- t(apply(df00[, c("Electability1", "Electability2")], MARGIN = 1, FUN = my_rescale2))


# 3) Manipulate ideological distance

# IDEOLOGY
df00[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")] <- square(df00[, c("Ideology1", "Ideology2")] - df00[, "Ideology"])

# rescale ideological distance

df00[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")] <- t(apply(df00[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")], MARGIN = 1, FUN = my_rescale1))


# 4) Average candidate traits

# TRAITS
df00$TRAITS1 = rowMeans(df00[, c("Cares1", "Honest1", "Inspire1", "Know1")], na.rm = TRUE) / 10
df00$TRAITS2 = rowMeans(df00[, c("Cares2", "Honest2", "Inspire2", "Know2")], na.rm = TRUE) / 10


# 5) Convert NaN to NA

df00[df00=="NaN"] <- NA

```
 
 
```{r}

# verify  calculations

df00[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "Feeling1", "Feeling2")]
df00[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", "Viability1", "Viability2")]
df00[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", "Electability1", "Electability2")]
df00[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", "Ideology1", "Ideology2")]
df00[, c("TRAITS1", "Cares1", "Honest1", "Inspire1", "Know1")]
df00[, c("TRAITS2", "Cares2", "Honest2", "Inspire2", "Know2")]

```
 
 
## Pivoting Data (Part Two)

```{r}

# 1) Subset: df00_normalized_ft

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2")
df <- df00[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df


# 2) Subset: df00_normalized_viability

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))

# convert VotingCandata to 1, 0
df_final$VoteCandidate <-  1 * (df_final$Candidate == df_final$VoteCandidate)

# 3) Subset: df00_normalized_electability

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))


# 4) Subset: df00_normalized_ideology

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))


# 5) Subset: df00_traits

my_cols <- c("ID", "TRAITS1", "TRAITS2")
df <- df00[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "TRAITS", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))

```


## Writing Cleaned Dataset

```{r}

df_final %>%
  drop_na() %>%
  write.dta("clean_data/df00_national_d.dta")

```


```{r include=FALSE}

rm(list=ls())

```

