---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)
library(foreign)

```


# Reading Data

```{r warning = FALSE}

# Reading in the three datasets.

anes80_mp <- spss.get("raw_data/anes/anes80-major-panel.por", use.value.labels=TRUE)

```


## Cleaning Data (Part One)

# ```{r}
# 
# # Cleaning the 1988 dataset
# # Case 0
# 
# anes88_st_clean_0 <- anes88_st %>%
#   
#   # Voting from VST0457 to VST0462
#   # Feeling thermometers from VST0171 to VST0189
#   # Traits from VST0301 to VST0424
#   # Ideology from VST0425 to VST0441
#   # Viability from VST0229 to VST0241
#   # Electability from VST0242 to VST0254
#   
#   select(VST0001, VST0457:VST0462, VST0171:VST0189, VST0301:VST0424,
#          VST0425:VST0441, VST0229:VST0241, VST0242:VST0254)
# 
# # Case 1
# 
# anes88_st_clean_1 <- anes88_st %>%
# 
#   # Voting from VST1528 to VST1561
#   # Feeling thermometers from VST1301 to VST1317
#   # Traits from VST1409 to VST1527
#   # Ideology not asked
#   # Viability from VST1322 to VST1331
#   # Electability from VST1332 to VST1341 
# 
#   select(VST1001, VST1528:VST1561, VST1301:VST1317, VST1409:VST1527,
#          VST1322:VST1331, VST1332:VST1341)
# 
# ```

## Cleaning Data (Part Two)

```{r}

df88st <- anes80_mp %>%
  
  # Select ID, voting, lib/con and feeling thermometer, viability, electability
  
  # Only includes Wave 1
  # Voting from VMP0205
  # Feeling thermometers from VMP0039 to VMP0044
  # Viability from VMP0192 to VMP0203 and from VMP0217 to VMP0231 (PROBLEM)
  # Electability from VMP0204 to VMP0205 and from VMP0232 to VMP0233 (PROBLEM)
  # Ideology MP0121 and from MP0122 to MP0129
  # Traits from VMP0074 to VMP0115
    
  select(MP0004, VST0459, 
         MP0039, MP0041, MP0044, 
         VST0229, VST0230, VST0231, 
         VST0242, VST0243, VST0244, 
         
         MP0121, 
         MP0122, MP0124, MP0127, 
         
         VST0304, VST0306, VST0307, VST0308, 
         VST0312, VST0314, VST0315, VST0316, 
         VST0320, VST0322, VST0323, VST0324
         )

my_candidate <- c("GORE","DUKAKIS","HART","JACKSON","GEPHARDT")
my_candidate_id <- as.integer(c(14, 12, 15, 16, 13))

my_names <- c("ID", "voting", 
              "Feeling1", "Feeling2", "Feeling3", "Feeling4", "Feeling5",
              "Viability1", "Viability2", "Viability3", "Viability4", 
              "Viability5",
              "Electability1", "Electability2", "Electability3", 
              "Electability4", "Electability5",
              
              "Ideology", 
              "Ideology1", "Ideology2", "Ideology3", "Ideology4", "Ideology5",
              
              "Inspire1", "Decent1", "Cares1", "Know1",
              "Inspire2", "Decent2", "Cares2", "Know2",
              "Inspire3", "Decent3", "Cares3", "Know3",
              "Inspire4", "Decent4", "Cares4", "Know4",
              "Inspire5", "Decent5", "Cares5", "Know5"
              )

colnames(df88st) <- my_names
```


```{r}
df <- data.frame(my_candidate_id, my_candidate, stringsAsFactors = FALSE)
df88st <-merge(df88st, df, by.x = "voting", 
               by.y = "my_candidate_id", all.x = TRUE)
names(df88st)[names(df88st)=="my_candidate"] <- "VoteCandidate"
```


```{r eval=FALSE, include=FALSE}

# verify column renaming, candidates and their number 1-5 mapping must be 
# correct.

str(df88st)

```


## Normalize ratings

```{r warning=FALSE}

# 1) Normalize feeling thermometers

my_rescale1 <- function(X) { 
  if (max(X, na.rm = TRUE) == min(X, na.rm = TRUE)) 
    X / sum(X, na.rm = TRUE)
  else
    round((X - min(X, na.rm = TRUE)) / 
            (max(X, na.rm = TRUE) - min(X, na.rm = TRUE)), 6)
}

df88st[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", 
           "NORMALIZED_FT4", "NORMALIZED_FT5")] <- t(apply(
             df88st[, c("Feeling1", "Feeling2", "Feeling3", "Feeling4", 
                        "Feeling5")], MARGIN = 1, FUN = my_rescale1))

# 2) Normalize viability

my_rescale2 <- function(X) round(X / sum(X, na.rm = TRUE), 6)

# NORMALIZED_VIABILITY
df88st[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", 
           "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", 
           "NORMALIZED_VIABILITY5")] <- t(apply(
             df88st[, c("Viability1", "Viability2", "Viability3", 
                        "Viability4", "Viability5")], 
             MARGIN = 1, FUN = my_rescale2))

# NORMALIZED_ELECTABILITY 
df88st[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
           "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", 
           "NORMALIZED_ELECTABILITY5")] <- t(apply(
             df88st[, c("Electability1", "Electability2", "Electability3", 
                        "Electability4", "Electability5")],
             MARGIN = 1, FUN = my_rescale2))

# 3) Manipulate ideological distance

df00[, c("temp_1", "temp_2")] <- square(
  df00[, c("Ideology1", "Ideology2")] - df00[, "Ideology"])

df00 <- df00 %>%
  rowwise() %>%
  mutate(temp_min = min(temp_1, temp_2)) %>%
  mutate(temp_max_min = max(temp_1, temp_2) - min(temp_1, temp_2)) %>%
  mutate(NORMALIZED_IDEOLOGY1 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_1 - temp_min) / 
                                               temp_max_min, 6))) %>%
  mutate(NORMALIZED_IDEOLOGY2 = ifelse(temp_max_min == 0,
                                       ifelse(temp_min == 0, 0, 0.5),
                                       round((temp_2 - temp_min) / 
                                               temp_max_min, 6))) %>%
  select(-starts_with("temp_") )

# 4) Average candidate traits

df88st$TRAITS1 = abs(rowMeans(
  df88st[, c("Inspire1", "Decent1", "Cares1", "Know1")], na.rm = TRUE) - 6) / 5
df88st$TRAITS2 = abs(rowMeans(
  df88st[, c("Inspire2", "Decent2", "Cares2", "Know2")], na.rm = TRUE) - 6) / 5
df88st$TRAITS3 = abs(rowMeans(
  df88st[, c("Inspire3", "Decent3", "Cares3", "Know3")], na.rm = TRUE) - 6) / 5
df88st$TRAITS4 = abs(rowMeans(
  df88st[, c("Inspire4", "Decent4", "Cares4", "Know4")], na.rm = TRUE) - 6) / 5
df88st$TRAITS5 = abs(rowMeans(
  df88st[, c("Inspire5", "Decent5", "Cares5", "Know5")], na.rm = TRUE) - 6) / 5

# 5) Convert NaN to NA

df88st[df88st == "NaN"] <- NA

```
 
 
```{r}

# Verify  calculations

df88st[, c("NORMALIZED_FT1", "NORMALIZED_FT2", "NORMALIZED_FT3", 
           "NORMALIZED_FT4", "NORMALIZED_FT5", "Feeling1", "Feeling2", 
           "Feeling3", "Feeling4", "Feeling5")]
df88st[, c("NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", 
           "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", 
           "NORMALIZED_VIABILITY5", "Viability1", "Viability2", 
           "Viability3", "Viability4", "Viability5")]
df88st[, c("NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
           "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", 
           "NORMALIZED_ELECTABILITY5", "Electability1", "Electability2", 
           "Electability3", "Electability4", "Electability5")]
df88st[, c("NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", 
           "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", 
           "NORMALIZED_IDEOLOGY5", "Ideology1", "Ideology2", "Ideology3", 
           "Ideology4", "Ideology5")]
df88st[, c("TRAITS1", "Inspire1", "Decent1", "Cares1", "Know1")]
df88st[, c("TRAITS2", "Inspire2", "Decent2", "Cares2", "Know2")]
df88st[, c("TRAITS3", "Inspire3", "Decent3", "Cares3", "Know3")]
df88st[, c("TRAITS4", "Inspire4", "Decent4", "Cares4", "Know4")]
df88st[, c("TRAITS5", "Inspire5", "Decent5", "Cares5", "Know5")]

```
 
 
## Pivoting Data (Part Two)

```{r}

# 1) Subset: df88st_normalized_ft

my_cols <- c("ID", "VoteCandidate", "NORMALIZED_FT1", "NORMALIZED_FT2", 
             "NORMALIZED_FT3", "NORMALIZED_FT4", "NORMALIZED_FT5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", "VoteCandidate", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_FT", 
               cols = -c(ID, VoteCandidate))
df_final <- df

# 2) Subset: df88st_normalized_viability

my_cols <- c("ID", "NORMALIZED_VIABILITY1", "NORMALIZED_VIABILITY2", 
             "NORMALIZED_VIABILITY3", "NORMALIZED_VIABILITY4", 
             "NORMALIZED_VIABILITY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_VIABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by=c("ID", "Candidate"))

# Convert VoteCandidate to 0, 1

df_final$VoteCandidate <-  1 * (df_final$Candidate == df_final$VoteCandidate)

# 3) Subset: df88st_normalized_electability

my_cols <- c("ID", "NORMALIZED_ELECTABILITY1", "NORMALIZED_ELECTABILITY2", 
             "NORMALIZED_ELECTABILITY3", "NORMALIZED_ELECTABILITY4", 
             "NORMALIZED_ELECTABILITY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_ELECTABILITY", 
               cols = -ID)

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# 4) Subset: df88st_normalized_ideology

my_cols <- c("ID", "NORMALIZED_IDEOLOGY1", "NORMALIZED_IDEOLOGY2", 
             "NORMALIZED_IDEOLOGY3", "NORMALIZED_IDEOLOGY4", 
             "NORMALIZED_IDEOLOGY5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "NORMALIZED_IDEOLOGY", 
               cols = -ID)

df_final = merge(df_final, df, by = c("ID", "Candidate"))

# 5) Subset: df88st_traits

my_cols <- c("ID", "TRAITS1", "TRAITS2", "TRAITS3", "TRAITS4", "TRAITS5")
df <- df88st[, my_cols]
colnames(df) <- c("ID", my_candidate)

df <- df %>%
  pivot_longer(names_to = "Candidate", 
               values_to = "TRAITS", 
               cols = -ID)

df_final = merge(df_final, df, by = c("ID", "Candidate"))

```


```{r}

# Create new columns using candidate names, assign 0 to all
df_final[, sort(my_candidate)] <- 0

# Get index when intersection column name/value matches
my_index <- cbind(seq_len(nrow(df_final)), 
                  match(df_final$Candidate, names(df_final)[-1]))

# Assign 1 to my_index cells
df_final[-1][my_index] <- 1

```


## Writing Cleaned Dataset

```{r}

df_final %>%
  drop_na() %>%
  write.dta("clean_data/df88st_d.dta")

```


# Calculating Buckets

```{r}

df_final_2 <- df_final %>%
  rowwise() %>%
  mutate(SINCERE = NORMALIZED_FT,
         STRATEGIC = (NORMALIZED_VIABILITY + NORMALIZED_ELECTABILITY) / 2) %>%
  select(ID, Candidate, VoteCandidate, SINCERE, STRATEGIC) %>%
  group_by(ID) %>%
  mutate(SINCERE_MAX1 = max(SINCERE),
         STRATEGIC_MAX1 = max(STRATEGIC)) %>%
  mutate(SINCERE_MAX2 = ifelse(SINCERE == SINCERE_MAX1, 1, 0),
         STRATEGIC_MAX2 = ifelse(STRATEGIC == STRATEGIC_MAX1, 1, 0)) %>%
  filter(VoteCandidate == 1) %>%
  drop_na()

```


```{r}

df_final_2 <- df_final_2 %>%
  group_by(Candidate, SINCERE_MAX2, STRATEGIC_MAX2) %>%
  count() %>%
  group_by(Candidate) %>%
  mutate(percent = n / sum(n))

df_final_2 %>%
  write.csv("clean_data/df00_ia_r_counts.csv")

```


```{r include=FALSE}

rm(list = ls())

```

