---
title: "anes"
author: "Ryan Zhang"
date: "10/12/2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(Hmisc)
library(rqPen)
library(vctrs)

```

# Reading Data

```{r warning = FALSE}

# Reading in the three datasets.

anes88_national <- spss.get("raw_data/anes/anes88-national.por", use.value.labels=TRUE)
anes88_st <- spss.get("raw_data/anes/anes88-super-tuesday.por", use.value.labels=TRUE)
anes84_national <- spss.get("raw_data/anes/anes84-national.por", use.value.labels=TRUE)
anes84_cm <- spss.get("raw_data/anes/anes84-continuous-monitoring.por", use.value.labels=TRUE)
anes80_national <- spss.get("raw_data/anes/anes80-national.por", use.value.labels=TRUE)
anes80_mp <- spss.get("raw_data/anes/anes80-major-panel.por", use.value.labels=TRUE)

```

# Cleaning Data (Part One)

```{r}

# Cleaning the 1988 dataset
# Case 0

anes88_st_clean_0 <- anes88_st %>%
  
  # Voting from VST0457 to VST0462
  # Feeling thermometers from VST0171 to VST0189
  # Traits from VST0301 to VST0424
  # Ideology from VST0425 to VST0441
  # Viability from VST0229 to VST0241
  # Electability from VST0242 to VST0254
  
  select(VST0001, VST0457:VST0462, VST0171:VST0189, VST0301:VST0424,
         VST0425:VST0441, VST0229:VST0241, VST0242:VST0254)

# Case 1

anes88_st_clean_1 <- anes88_st %>%

  # Voting from VST1528 to VST1561
  # Feeling thermometers from VST1301 to VST1317
  # Traits from VST1409 to VST1527
  # Ideology not asked
  # Viability from VST1322 to VST1331
  # Electability from VST1332 to VST1341 

  select(VST1001, VST1528:VST1561, VST1301:VST1317, VST1409:VST1527,
         VST1322:VST1331, VST1332:VST1341)

# Cleaning the 1984 dataset

anes84_cm_clean <- anes84_cm %>%
  
  # Voting from VCM0735 to VCM0736.
  # Feeling thermometers from VCM0219 to VCM0236.
  # Traits from VCM0418 to VCM0573
  # Ideology from VCM0610 to VCM0637.
  # Viability from VCM0311 to VCM0316.
  # Electability from VCM1001 to VCM1007.

  select(VCM0001, VCM0735:VCM0736, VCM0219:VCM0236,
         VCM0418:VCM0573, VCM0610:VCM0637, VCM0311:VCM0316, VCM1001:VCM1007)
  
# Cleaning the 1980 dataset.

anes80_mp_clean <- anes80_mp %>%

  # TODO
  # Voting from VMP4078 to VMP4079
  # Feeling thermometers from VMP3095 to VMP3112
  # Traits from VMP0074 to VMP0115
  # Ideology from VMP2125 to VMP2136
  # Viability from VMP0192 to VMP0203 and from VMP0217 to VMP0231
  # Electability from VMP0204 to VMP0205 and from VMP0232 to VMP0233

  select(VMP4078:VMP4079, VMP3095:VMP3112, VMP0074:VMP0115,
         VMP2125:VMP2136, VMP0192:VMP0203, VMP0217:VMP0231,
         VMP0204:VMP0205, VMP0232:VMP0233)

```

# Cleaning Data (Part Two)

```{r}

# Cleaning 1988 case 0

anes88_st_clean_0_d <- anes88_st_clean_0 %>%
  
  # Select ID, voting, feeling thermometer, viability, electability, and columns
  
  select(VST0001, VST0459,
         VST0171, VST0172, VST0173, VST0175, VST0176,
         VST0229, VST0230, VST0231, VST0233, VST0234,
         VST0242, VST0243, VST0244, VST0246, VST0247,
         VST0425, VST0428, VST0429, VST0430, VST0432, VST0433,
         VST0304, VST0306:VST0308, VST0312, VST0314:VST0316, VST0320, VST0322:VST0324, VST0336, VST0338:VST0340, VST0344, VST0346:VST0348) %>%

  # VST0301:VST0309, VST0310:VST0318, VST0319:VST0327, VST0333:VST0340, VST0341:VST0348) %>%
  
  # Normalize feeling thermometers
    
  rowwise(VST0001) %>%
  mutate(normalized_ft_gore = (VST0171 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) / 
           (max(VST0171, VST0172, VST0173, VST0175, VST0176) -
              min(VST0171, VST0172, VST0173, VST0175, VST0176)),
         normalized_ft_dukakis = (VST0172 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) / 
           (max(VST0171, VST0172, VST0173, VST0175, VST0176) -
              min(VST0171, VST0172, VST0173, VST0175, VST0176)),
         normalized_ft_hart = (VST0173 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) / 
           (max(VST0171, VST0172, VST0173, VST0175, VST0176) -
              min(VST0171, VST0172, VST0173, VST0175, VST0176)),
         normalized_ft_jackson = (VST0175 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) / 
           (max(VST0171, VST0172, VST0173, VST0175, VST0176) -
              min(VST0171, VST0172, VST0173, VST0175, VST0176)),
         normalized_ft_gephardt = (VST0176 - max(VST0171, VST0172, VST0173, VST0175, VST0176)) / 
           (max(VST0171, VST0172, VST0173, VST0175, VST0176) -
              min(VST0171, VST0172, VST0173, VST0175, VST0176))) %>%
  drop_na(normalized_ft_gore) %>%

  # Normalize viability

  rowwise(VST0001) %>%
  mutate(normalized_viability_gore = VST0229 / sum(VST0229, VST0230, VST0231, VST0233, VST0234),
         normalized_viability_dukakis = VST0230 / sum(VST0229, VST0230, VST0231, VST0233, VST0234),
         normalized_viability_hart = VST0231 / sum(VST0229, VST0230, VST0231, VST0233, VST0234),
         normalized_viability_jackson = VST0233 / sum(VST0229, VST0230, VST0231, VST0233, VST0234),
         normalized_viability_gephardt = VST0234 / sum(VST0229, VST0230, VST0231, VST0233, VST0234)) %>%
  drop_na(normalized_viability_gore) %>%

  # Normalize electability

  rowwise(VST0001) %>%
  mutate(normalized_electability_gore = VST0242 / sum(VST0242, VST0243, VST0244, VST0246, VST0247),
         normalized_electability_dukakis = VST0243 / sum(VST0242, VST0243, VST0244, VST0246, VST0247),
         normalized_electability_hart = VST0244 / sum(VST0242, VST0243, VST0244, VST0246, VST0247),
         normalized_electability_jackson = VST0246 / sum(VST0242, VST0243, VST0244, VST0246, VST0247),
         normalized_electability_gephardt = VST0247 / sum(VST0242, VST0243, VST0244, VST0246, VST0247)) %>%
  drop_na(normalized_electability_gore) %>%
  
  # Manipulate ideological distance

  rowwise(VST0001) %>%
  mutate(ideology_gore = square(VST0425 - VST0428),
         ideology_dukakis = square(VST0425 - VST0429),
         ideology_hart = square(VST0425 - VST0430),
         ideology_jackson = square(VST0425 - VST0432),
         ideology_gephardt = square(VST0425 - VST0433)) %>%
  
  # Average candidate traits

  rowwise(VST0001)
  mutate(traits_gore = mean(VST0304, VST0306, VST0307, VST0308),
         traits_dukakis = mean(VST0312, VST0314, VST0315, VST0316),
         traits_hart = mean(VST0320, VST0322, VST0323, VST0324),
         traits_jackson = mean(VST0336, VST0338, VST0339, VST0340),
         traits_gephardt = mean(VST0344, VST0346, VST0347, VST0348)) 
```

Need to scale ideological distance. 

# Pivoting Data (Part Two)

```{r}

anes88_st_clean_0_d_pivot <- anes88_st_clean_0_d %>%
  select(VST0001, VST0459, 67:91) %>%
  na.omit() %>%
  pivot_longer(cols = c(normalized_ft_gore, normalized_ft_dukakis,
                        normalized_ft_hart, normalized_ft_jackson, normalized_ft_gephardt),
               names_to = "candidate", values_to = "normalized_ft")



```

